### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by djayci** [budliter/HomeBridge-NeoSmartShades#2]
Hey there!

I'm trying to get your plugin to work but it just doesn't.
I can see traffic coming through homebridge as 

Sent Command: 136.055-03-dn at time: 18:42:04 

however, the blinds don't move a bit.
This is my config

 "platform": "NEOShades",
            "name": "NEOShades",
            "host": "192.168.1.200", // I got this from the app
            "controllerID": "2b0042000347393032323330", // I got this from the app too
            "shades": [
                {
                    "name": "Bedroom left blind",
                    "code": "136.055-01" //the blind ID from the app
                },
                {
                    "name": "Bedroom right blind",
                    "code": "136.055-03"
                }
            ]

Any idea on how to debug it?

**Comment by budliter** [comment]
Unfortunately, I do not know what the problem is or how to debug this.  Recommend you trying using the original version that I reference in the supporting text to see if that version works.  This version is a small adaptation of the original to enable the use of favorite positions...so I can't fully help you debug.
